# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\setRTCdesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QFrame(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, -10, 480, 640))
        self.background.setStyleSheet("background-color: rgb(255, 255,255)")
        self.background.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background.setObjectName("background")
        self.Btn_Send = QtWidgets.QPushButton(self.background)
        self.Btn_Send.setGeometry(QtCore.QRect(40, 480, 400, 40))
        self.Btn_Send.setStyleSheet("background-color: rgb(221, 221, 221)")
        self.Btn_Send.setObjectName("Btn_Send")
        self.label = QtWidgets.QLabel(self.background)
        self.label.setGeometry(QtCore.QRect(70, 20, 340, 120))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background :url(:/newPrefix/edgetitle.png)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.background)
        self.widget.setGeometry(QtCore.QRect(40, 150, 400, 300))
        self.widget.setStyleSheet("background : rgb(255, 255, 255);\n"
"border: 1px solid black")
        self.widget.setObjectName("widget")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(100, 140, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(160, 110, 64, 15))
        self.label_2.setStyleSheet("border: 0px")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(1, 1, 390, 40))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: 0px")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.menu.addAction(self.actionclose)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Send.setText(_translate("MainWindow", "Send"))
        self.label_2.setText(_translate("MainWindow", "Input time"))
        self.label_3.setText(_translate("MainWindow", "SET RTC"))
        self.menu.setTitle(_translate("MainWindow", "메뉴"))
        self.actionclose.setText(_translate("MainWindow", "close"))
import grx_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
